# Generated by Django 3.2.9 on 2022-03-20 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cataory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Coures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours_name', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='pics')),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.cataory')),
            ],
        ),
        migrations.CreateModel(
            name='Tutoris',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=300)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.coures')),
            ],
        ),
    ]
