# Generated by Django 3.2.9 on 2022-03-20 19:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoris',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
