# Generated by Django 3.2.9 on 2022-03-20 22:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_tutoris_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutoris',
            name='body',
        ),
        migrations.CreateModel(
            name='Bodycors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('select_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.coures')),
                ('select_titel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.tutoris')),
            ],
        ),
    ]
